name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "**.ts"
      - "**.tsx"
      - "**.js"
      - "**.jsx"
      - "**.json"
      - "**.yml"

jobs:
  gpt-review:
    if: contains(github.event.pull_request.labels.*.name, 'gptReview')
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Japanese
          OPENAI_API_ENDPOINT: https://api.openai.com/v1
          MODEL: gpt-4-turbo
          PROMPT: |
            あなたはベテランのReact + TypeScriptエンジニアです。回答は日本語でお願いします。
            渡されたコードについて以下の観点から改善点を見つけ、変更する理由を説明した上で、変更後のコード例を示してください。
            改善点がない場合には絶対にコメントをしないでください。

            対象とするファイルは `**.ts`、`**.tsx`、`**.js`、`**.jsx`、`**.json`、および `**.yml` です。
            それ以外のファイルにはコメントしないでください。

            **レビュー観点**:
              - コンポーネントや関数の命名が適切で分かりやすいか
              - 型定義が適切で冗長または不足がないか
              - 冗長なコードや無駄なロジックがないか
              - Reactのライフサイクルやフックの適切な使用がされているか
              - PropsやStateが適切に設計されているか
              - `useEffect`や`useState`などのフックが正しく使われているか
              - 必要に応じて型ガードが実装されているか
              - コメントが適切に記述され、理解が容易であるか
              - JSONファイルや設定ファイルで不要なキーや値が含まれていないか
              - セキュリティ上のリスク（例: 不要な依存性、ハードコーディングされた値など）がないか
              - テストコードが記述されており、その説明が内容を適切に反映しているか

            他のエンジニアが読みやすく、保守しやすいコードになるように積極的に指摘してください。
            渡されるコードは一部である可能性が高いため、外部依存や未定義の関数/変数については消極的に指摘してください。
          top_p: 1
          temperature: 0.7
          max_tokens: 4096
          MAX_PATCH_LENGTH: 4096
